In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
categorical = pd.read_csv('files_for_lab/categorical.csv')
numerical = pd.read_csv('files_for_lab/numerical.csv')
target = pd.read_csv('files_for_lab/target.csv')

data = pd.concat([categorical,numerical,target],axis=1)

In [3]:
display(data.head(),print('data.shape:',data.shape))

data.shape: (95412, 339)


STATE  CLUSTER HOMEOWNR GENDER  DATASRCE RFA_2R RFA_2A GEOCODE2 DOMAIN_A  \
0    IL       36        H      F         3      L      E        C        T   
1    CA       14        H      M         3      L      G        A        S   
2    NC       43        U      M         3      L      E        C        R   
3    CA       44        U      F         3      L      E        C        R   
4    FL       16        H      F         3      L      F        A        S   

   DOMAIN_B  ...  MAXRAMNT  LASTGIFT  TIMELAG    AVGGIFT  CONTROLN  HPHONE_D  \
0         2  ...      12.0      10.0        4   7.741935     95515         0   
1         1  ...      25.0      25.0       18  15.666667    148535         0   
2         2  ...      16.0       5.0       12   7.481481     15078         1   
3         2  ...      11.0      10.0        9   6.812500    172556         1   
4         2  ...      15.0      15.0       14   6.864865      7112         1   

   RFA_2F  CLUSTER2  TARGET_B  TARGET_D  
0       4        39         0       0.0  
1       2         1         0       0.0  
2       4        60         0       0.0  
3       4        41         0       0.0  
4       2        26         0       0.0  

[5 rows x 339 columns]

None

In [4]:
data.isna().sum().sum()

0

In [5]:
data[data['FIRSTDATE_MM'].isna()] 

Empty DataFrame
Columns: [STATE, CLUSTER, HOMEOWNR, GENDER, DATASRCE, RFA_2R, RFA_2A, GEOCODE2, DOMAIN_A, DOMAIN_B, ODATEW_YR, ODATEW_MM, DOB_YR, DOB_MM, MINRDATE_YR, MINRDATE_MM, MAXRDATE_YR, MAXRDATE_MM, LASTDATE_YR, LASTDATE_MM, FIRSTDATE_YR, FIRSTDATE_MM, TCODE, AGE, INCOME, WEALTH1, HIT, MALEMILI, MALEVET, VIETVETS, WWIIVETS, LOCALGOV, STATEGOV, FEDGOV, WEALTH2, POP901, POP902, POP903, POP90C1, POP90C2, POP90C3, POP90C4, POP90C5, ETH1, ETH2, ETH3, ETH4, ETH5, ETH6, ETH7, ETH8, ETH9, ETH10, ETH11, ETH12, ETH13, ETH14, ETH15, ETH16, AGE901, AGE902, AGE903, AGE904, AGE905, AGE906, AGE907, CHIL1, CHIL2, CHIL3, AGEC1, AGEC2, AGEC3, AGEC4, AGEC5, AGEC6, AGEC7, CHILC1, CHILC2, CHILC3, CHILC4, CHILC5, HHAGE1, HHAGE2, HHAGE3, HHN1, HHN2, HHN3, HHN4, HHN5, HHN6, MARR1, MARR2, MARR3, MARR4, HHP1, HHP2, DW1, DW2, DW3, DW4, ...]
Index: []

[0 rows x 339 columns]

In [6]:
data['TARGET_B'].value_counts()

0    90569
1     4843
Name: TARGET_B, dtype: int64

In [7]:
from sklearn.utils import resample

category_0 = data[data['TARGET_B'] == 0]
category_1 = data[data['TARGET_B'] == 1]

category_1_oversampled = resample(category_1, 
                                  replace=True, # Wichtig an diesem punkt! downsampling False
                                  n_samples = len(category_0))

print('Not Donate', category_0.shape)
print('Do Donate oversampled', category_1_oversampled.shape)

Not Donate (90569, 339)
Do Donate oversampled (90569, 339)


In [8]:
data_upsampled = pd.concat([category_0, category_1_oversampled], axis=0)
data_upsampled['TARGET_B'].value_counts()

1    90569
0    90569
Name: TARGET_B, dtype: int64

In [9]:
X = data_upsampled.drop(['TARGET_B','TARGET_D'], axis = 1)
y = data_upsampled['TARGET_B']

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [11]:
X_train_num = X_train.select_dtypes(include = np.number)
X_train_cat = X_train.select_dtypes(object)

In [12]:
X_test_num = X_test.select_dtypes(include = np.number)
X_test_cat = X_test.select_dtypes(object)

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
#create transformer
transformer = StandardScaler().fit(X_train_num)
x_standardized = transformer.transform(X_train_num)

In [15]:
#X_train
print(x_standardized.shape)
X_train_num_scaled = pd.DataFrame(x_standardized, columns=X_train_num.columns)

(126796, 330)


In [16]:
#X_test
X_test_num_scaled = pd.DataFrame(transformer.transform(X_test_num), columns=X_train_num.columns)

In [17]:
from sklearn.preprocessing import OneHotEncoder

In [18]:
#create encoder
encoder = OneHotEncoder(drop='first').fit(X_train_cat)

In [19]:
#columns names
cols_cat = encoder.get_feature_names_out(input_features=X_train_cat.columns)

In [20]:
#train
encoded_train = encoder.transform(X_train_cat).toarray()
encoded_train = pd.DataFrame(encoded_train,columns=cols_cat)

In [21]:
#test
encoded_test = encoder.transform(X_test_cat).toarray()
encoded_test = pd.DataFrame(encoded_test,columns=cols_cat)

In [22]:
train_scaled = pd.concat([encoded_train,X_train_num_scaled],axis=1)
test_scaled = pd.concat([encoded_test,X_test_num_scaled],axis=1)
df = pd.concat([test_scaled,train_scaled],axis=0)
pd.set_option('display.max_columns', None)
display(df.head(3),print('X.shape:',df.shape))

X.shape: (181138, 354)


STATE_FL  STATE_GA  STATE_IL  STATE_IN  STATE_MI  STATE_MO  STATE_NC  \
0       0.0       0.0       0.0       0.0       0.0       0.0       0.0   
1       0.0       0.0       0.0       0.0       0.0       0.0       0.0   
2       0.0       0.0       0.0       0.0       0.0       0.0       0.0   

   STATE_TX  STATE_WA  STATE_WI  STATE_other  HOMEOWNR_U  GENDER_M  \
0       0.0       0.0       0.0          0.0         0.0       1.0   
1       0.0       0.0       0.0          0.0         0.0       0.0   
2       0.0       0.0       0.0          0.0         0.0       1.0   

   GENDER_other  RFA_2A_E  RFA_2A_F  RFA_2A_G  GEOCODE2_B  GEOCODE2_C  \
0           0.0       0.0       0.0       1.0         0.0         0.0   
1           0.0       0.0       0.0       0.0         0.0         0.0   
2           0.0       0.0       0.0       1.0         0.0         0.0   

   GEOCODE2_D  DOMAIN_A_R  DOMAIN_A_S  DOMAIN_A_T  DOMAIN_A_U   CLUSTER  \
0         0.0         1.0         0.0         0.0         0.0  1.183886   
1         0.0         0.0         1.0         0.0         0.0 -1.117617   
2         0.0         0.0         0.0         0.0         1.0 -1.396587   

   DATASRCE  DOMAIN_B  ODATEW_YR  ODATEW_MM    DOB_YR    DOB_MM  MINRDATE_YR  \
0  0.627309  0.157195   0.526801  -0.031352 -1.319702 -0.306382     1.330457   
1 -0.973195 -1.216834  -0.055421  -0.031352  1.460824 -0.631604    -0.537971   
2 -0.973195  1.531224  -0.055421  -0.031352  0.997403  2.620613    -0.164285   

   MINRDATE_MM  MAXRDATE_YR  MAXRDATE_MM  LASTDATE_YR  LASTDATE_MM  \
0    -0.613008     0.962329    -1.493046     2.832821    -1.284017   
1     0.678099    -0.691313     0.761000     0.994016    -1.284017   
2     1.194541     0.411115     1.261899    -0.844790     1.273035   

   FIRSTDATE_YR  FIRSTDATE_MM     TCODE       AGE    INCOME   WEALTH1  \
0      0.595539     -1.036359 -0.058589 -0.018594 -1.885385 -2.262037   
1     -0.029162      0.741851 -0.059547 -1.686210  1.668141  0.716440   
2     -0.029162      1.249911 -0.058589 -1.050569 -0.108622  0.716440   

        HIT  MALEMILI   MALEVET  VIETVETS  WWIIVETS  LOCALGOV  STATEGOV  \
0  2.032417 -0.211264  0.553797 -0.035269  0.616339  0.970337 -0.499983   
1 -0.361117 -0.005452 -0.572516  1.875948 -1.217790  0.280743 -0.304057   
2 -0.361117  0.200360 -0.485876  0.162443 -0.439675 -0.638716 -0.304057   

     FEDGOV   WEALTH2    POP901    POP902    POP903   POP90C1   POP90C2  \
0  0.724801 -2.040631 -0.207292 -0.195631 -0.262129  0.838946 -0.432842   
1  0.971538  0.060950 -0.223894 -0.228260 -0.237724  0.838946 -0.432842   
2  0.478065 -1.340104 -0.031349 -0.101291 -0.151587  0.838946 -0.432842   

    POP90C3   POP90C4   POP90C5      ETH1      ETH2      ETH3      ETH4  \
0 -0.643463  0.322317 -0.177783 -0.081881 -0.371147 -0.231271  1.582454   
1 -0.643463 -0.048332  0.180364 -2.082038  0.460102  0.080506  5.017609   
2 -0.643463  0.322317 -0.177783 -1.381983  0.012506  0.080506  2.441243   

       ETH5      ETH6      ETH7      ETH8       ETH9     ETH10    ETH11  \
0  0.115598 -0.329009  2.046227  0.551942   1.120890  1.535540  0.82639   
1  0.189705  1.199423  0.707642  2.947136  10.769021 -0.238673  0.82639   
2  1.745954  2.727854  0.261447  1.350340   2.499194  4.196859  0.82639   

      ETH12     ETH13     ETH14     ETH15     ETH16    AGE901    AGE902  \
0 -0.057865  0.172423 -0.244939 -0.102168 -0.161921  0.144969  0.223258   
1 -0.057865 -0.098777 -0.244939 -0.102168  1.054495 -0.570993 -0.991015   
2 -0.057865  1.890028  0.563528 -0.102168  0.446287 -0.928973 -0.869587   

     AGE903    AGE904    AGE905    AGE906    AGE907     CHIL1     CHIL2  \
0  0.208538 -0.019867 -0.127935 -0.005689 -0.176817 -0.944700  0.578933   
1 -1.153815 -0.983735 -1.000404 -1.333654  0.355859  1.751449 -0.849565   
2 -0.782264 -0.846039 -0.854993 -0.743447  0.755366  0.771032 -0.373399   

      CHIL3     AGEC1     AGEC2     AGEC3     AGEC4     AGEC5     AGEC6  \
0  1.077914  0.162831 -0.519639 -0.271330  1.602893

None

### Random Forest Classifier

In [23]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

clf = RandomForestClassifier(max_depth=5,
                             min_samples_split=20,
                             min_samples_leaf =20)
clf.fit(train_scaled, y_train)
print(clf.score(train_scaled, y_train))
print(clf.score(test_scaled, y_test))

y_pred = clf.predict(test_scaled)
display(y_test.value_counts())
display(confusion_matrix(y_test, y_pred))

0.615058834663554
0.6133009458613964


1    27415
0    26927
Name: TARGET_B, dtype: int64

array([[16894, 10033],
       [10981, 16434]], dtype=int64)

### Cross Validation Score

In [24]:
from sklearn.model_selection import cross_val_score
clf = RandomForestClassifier(max_depth=5,
                             min_samples_split=20,
                             min_samples_leaf =20)
cross_val_scores = cross_val_score(clf, train_scaled, y_train, cv=10)
print(np.mean(cross_val_scores))
print(cross_val_scores)

0.6121644473847437
[0.6137224  0.60757098 0.60473186 0.61309148 0.6115142  0.61908517
 0.61495386 0.61597918 0.60777664 0.61321871]


In [25]:
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix

In [26]:
print('prediction:', precision_score(y_test,y_pred))
print('recall:', recall_score(y_test,y_pred))
print('f1:', f1_score(y_test,y_pred))

prediction: 0.6209241697207843
recall: 0.5994528542768557
f1: 0.6099996288185294


In [27]:
display(confusion_matrix(y_test, y_pred))

array([[16894, 10033],
       [10981, 16434]], dtype=int64)

In [28]:
# 16786 -> donate
# 10853 -> would donate but predict as not donate
# 10141 -> wouldn't donate but predict as donate
# 16562 -> wouldn't donate 
tp = 16786
fp = 10853
fn = 10141
tn = 16562

In [29]:
len(data[data['TARGET_D']>0])

4843

In [30]:
donate_mean_p_person = data[data['TARGET_D']!=0]['TARGET_D'].mean()
print(round(donate_mean_p_person,2))
# mean donation of one donating person 15.62$

15.62


# Lab | Final regression model in "Health Care for All" Case

In [32]:
import warnings
warnings.filterwarnings('ignore')

from sklearn.tree import DecisionTreeRegressor
model1 = DecisionTreeRegressor()
from sklearn.linear_model import LinearRegression
model2 = LinearRegression()
from sklearn.neighbors import KNeighborsRegressor
model3 = KNeighborsRegressor()

import numpy as np

# X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.25)

# data should really be scaled here
model_pipeline = [model1, model2, model3]
model_names = ['Decision Tree Regressor', 'Linear Regression', 'KNN']
scores = {}
for model, model_name in zip(model_pipeline, model_names):
    mean_score = np.mean(cross_val_score(model, train_scaled, y_train, cv=10))
    scores[model_name] = mean_score
print(scores)

# We can use the result to choose the best performing model

{'Decision Tree Regressor': 0.8325305622446713, 'Linear Regression': 0.05809772395290701, 'KNN': nan}


In [33]:
list(zip(model_pipeline, model_names))

[(DecisionTreeRegressor(), 'Decision Tree Regressor'),
 (LinearRegression(), 'Linear Regression'),
 (KNeighborsRegressor(), 'KNN')]

In [34]:
val_scores = {}

for model, model_name in zip(model_pipeline,model_names):
    model.fit(train_scaled, y_train)
    val_scores[model_name] = model.score(test_scaled,y_test)
print(val_scores)

{'Decision Tree Regressor': 0.8505639307242436, 'Linear Regression': 0.06594773466548043, 'KNN': 0.7181326555384873}


In [35]:
pred=DecisionTreeRegressor().fit(train_scaled,y_train).predict(test_scaled)

In [36]:
display(len(pred),len(y_test))

54342

54342

In [37]:
from sklearn.metrics import r2_score

print('R2 Score:', r2_score(y_test, pred))

R2 Score: 0.8514472966509969


In [38]:
display(confusion_matrix(y_test, pred))

array([[24909,  2018],
       [    0, 27415]], dtype=int64)

In [43]:
# 24890 -> donate
# 0     -> would donate but predict as not donate
# 2037  -> wouldn't donate but predict as donate
# 27415 -> wouldn't donate 
tp = 16786
fp = 0
fn = 2037
tn = 27415

post_cost=0.68

In [44]:
x = round((tn * donate_mean_p_person),2)
print('Amount saved money if use model:',round((x),2),'$')

Amount saved money if use model: 428341.4 $


In [45]:
x = round((fp * donate_mean_p_person),2)
print('Amount lost money if use model:',round((x),2),'$')

Amount lost money if use model: 0.0 $


In [46]:
x = round(((fn+tn)*post_cost),2)
print('Money to send Post:',round((x),2),'$')

Money to send Post: 20027.36 $


In [47]:
x = round((fn*post_cost),2)
print('Money to send Post for people who not donate:',round((x),2),'$')

Money to send Post for people who not donate: 1385.16 $
